[GeneralSettings]
    ServerPort = 8079
    RequestTimeoutSec = 10
    HeartbeatCacheValidityDurationSec = 25
    ValStatsCacheValidityDurationSec = 60
    EconomicsMetricsCacheValidityDurationSec = 600
    FaucetValue = "0"
    RateLimitWindowDurationSeconds = 60
    BalancedObservers = true
    BalancedFullHistoryNodes = true
    AllowEntireTxPoolFetch = false

[AddressPubkeyConverter]
    Length = 32
    Type = "bech32"

[Marshalizer]
    Type = "gogo protobuf"

[Hasher]
    Type = "blake2b"

[ApiLogging]
    LoggingEnabled = false
    ThresholdInMicroSeconds = 100

# Shard 0 Observer
[[Observers]]
    ShardId = 0
    Address = "http://10.0.0.6:8080"

# Shard 1 Observer
[[Observers]]
    ShardId = 1
    Address = "http://10.0.0.5:8080"

# Shard 2 Observer
[[Observers]]
    ShardId = 2
    Address = "http://10.0.0.4:8080"

# Metachain Observer
[[Observers]]
    ShardId = 4294967295
    Address = "http://10.0.0.3:8080"
